version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: crypto_failures_db
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
