spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crypto_failures_db?createDatabaseIfNotExist=true
    username: root
    password: admin
    drive-class-name: org.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
